demo_redshift_tpch:
  target: dev
  outputs:
    dev:
      type: redshift
      host: dbtcluster2-2rdusxwdddic.ccv1v6o4auql.us-east-1.redshift.amazonaws.com
      user: awsuser
      password: Awsuser12#
      port: 5439
      dbname: dev
      schema: tpch
      threads: 4
      keepalives_idle: 240 # default 240 seconds
      connect_timeout: 10 # default 10 seconds
      ra3_node: true # enables cross-database sources