demo_redshift_tpch:
  target: dev
  outputs:
    dev:
      type: redshift
      host: "{{ env_var('DB_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 5439
      dbname: "{{ env_var('DB_NAME') }}"
      schema: "{{ env_var('SCHEMA_NAME') }}"
      threads: 4
      keepalives_idle: 240 # default 240 seconds
      connect_timeout: 10 # default 10 seconds
      ra3_node: true # enables cross-database sources